/*
================================================================================
PRODUCTION-READY: PREPARE DATA FOR ROBUST XGBOOST ANALYSIS
PURPOSE: This query creates a single, comprehensive modeling dataset by aggregating
         event-level data and engineering features for machine learning.

Key Features:
- Aggregates daily event data to a single row per member per day.
- Corrects for duplicate rows that can arise from event-level data.
- Creates new features, including time-based data, one-hot encoded
  categorical variables, and specific HCC flags.
- Includes a key feature ('HAS_CARE_NOTES_POST_PERIOD') to isolate the
  predictive impact of care notes.
- Splits the data into 'TRAIN' and 'TEST' sets based on a member-level split,
  not a time cutoff.

Assumptions:
- 'EVENTS_DAILY_AGG' and 'EVENTS_WITH_LABELS_RX' are pre-existing tables.
================================================================================
*/

-- Define the final table for our modeling dataset.
CREATE OR REPLACE TABLE TRANSFORMED_DATA._TEMP.MODELING_DATASET AS
WITH daily_agg AS (
    -- Step 1: Aggregate the EVENTS_DAILY_AGG table to ensure one row per member per day.
    -- This CTE is a crucial step to prevent duplicates from joins on event-level data.
    SELECT
        MEMBER_ID,
        EVENT_DATE,
        DOB,
        -- Corrected: Standardize categorical text by replacing special characters and converting to uppercase.
        UPPER(TRIM(REPLACE(GENDER, ' ', ' '))) AS GENDER,
        UPPER(TRIM(REPLACE(ENGAGEMENT_GROUP, ' ', ' '))) AS ENGAGEMENT_GROUP,
        UPPER(TRIM(REPLACE(NORMALIZED_COVERAGE_CATEGORY, ' ', ' '))) AS NORMALIZED_COVERAGE_CATEGORY,
        -- All other columns are aggregated to get a single value per member-day.
        MAX(MONTHS_SINCE_BATCHED) AS MONTHS_SINCE_BATCHED,
        SUM(CNT_CLAIM_DX) AS CNT_CLAIM_DX,
        SUM(CNT_CLAIM_PROC) AS CNT_CLAIM_PROC,
        SUM(CNT_CLAIM_REV) AS CNT_CLAIM_REV,
        SUM(CNT_CLAIM_EVENTS) AS CNT_CLAIM_EVENTS,
        MAX(ANY_ED_ON_DATE) AS ANY_ED_ON_DATE,
        MAX(ANY_IP_ON_DATE) AS ANY_IP_ON_DATE,
        SUM(PAID_SUM) AS PAID_SUM,
        SUM(CNT_HCC_DIABETES) AS CNT_HCC_DIABETES,
        SUM(CNT_HCC_MENTAL_HEALTH) AS CNT_HCC_MENTAL_HEALTH,
        SUM(CNT_HCC_CARDIOVASCULAR) AS CNT_HCC_CARDIOVASCULAR,
        SUM(CNT_HCC_PULMONARY) AS CNT_HCC_PULMONARY,
        SUM(CNT_HCC_KIDNEY) AS CNT_HCC_KIDNEY,
        SUM(CNT_HCC_SUD) AS CNT_HCC_SUD,
        SUM(CNT_ANY_HCC) AS CNT_ANY_HCC,
        SUM(CNT_PROC_PSYCHOTHERAPY) AS CNT_PROC_PSYCHOTHERAPY,
        SUM(CNT_PROC_PSYCHIATRIC_EVALS) AS CNT_PROC_PSYCHIATRIC_EVALS,
        -- Averages are used for scores as there may be multiple per day.
        AVG(NOTE_HEALTH_SCORE) AS NOTE_HEALTH_SCORE,
        AVG(NOTE_RISK_HARM_SCORE) AS NOTE_RISK_HARM_SCORE,
        AVG(NOTE_SOCIAL_STAB_SCORE) AS NOTE_SOCIAL_STAB_SCORE,
        AVG(NOTE_MED_ADHERENCE_SCORE) AS NOTE_MED_ADHERENCE_SCORE,
        AVG(NOTE_CARE_ENGAGEMENT_SCORE) AS NOTE_CARE_ENGAGEMENT_SCORE,
        AVG(NOTE_PROGRAM_TRUST_SCORE) AS NOTE_PROGRAM_TRUST_SCORE,
        AVG(NOTE_SELF_SCORE) AS NOTE_SELF_SCORE,
        MAX(HEALTH_POP_BASELINE) AS HEALTH_POP_BASELINE,
        MAX(HEALTH_INDIV_BASELINE) AS HEALTH_INDIV_BASELINE,
        SUM(RX_DAYS_ANY) AS RX_DAYS_ANY,
        SUM(RX_DAYS_ANTIPSYCH) AS RX_DAYS_ANTIPSYCH,
        SUM(RX_DAYS_INSULIN) AS RX_DAYS_INSULIN,
        SUM(RX_DAYS_ORAL_ANTIDIAB) AS RX_DAYS_ORAL_ANTIDIAB,
        SUM(RX_DAYS_STATIN) AS RX_DAYS_STATIN,
        SUM(RX_DAYS_BETA_BLOCKER) AS RX_DAYS_BETA_BLOCKER,
        SUM(RX_DAYS_OPIOID) AS RX_DAYS_OPIOID,
        MAX(INCONSISTENCY_MED_NONCOMPLIANCE) AS INCONSISTENCY_MED_NONCOMPLIANCE,
        MAX(INCONSISTENCY_APPT_NONCOMPLIANCE) AS INCONSISTENCY_APPT_NONCOMPLIANCE,
        MAX(Y_ANY_30D) AS Y_ANY_30D,
        MAX(Y_ANY_60D) AS Y_ANY_60D,
        MAX(Y_ANY_90D) AS Y_ANY_90D,
        MAX(Y_ED_30D) AS Y_ED_30D,
        MAX(Y_ED_60D) AS Y_ED_60D,
        MAX(Y_ED_90D) AS Y_ED_90D,
        MAX(Y_IP_30D) AS Y_IP_30D,
        MAX(Y_IP_60D) AS Y_IP_60D,
        MAX(Y_IP_90D) AS Y_IP_90D
    FROM TRANSFORMED_DATA._TEMP.EVENTS_DAILY_AGG
    GROUP BY
        MEMBER_ID, EVENT_DATE, DOB, GENDER, ENGAGEMENT_GROUP,
        NORMALIZED_COVERAGE_CATEGORY
),
longitudinal_features AS (
    -- Step 2: Create advanced longitudinal features for the model.
    -- This CTE adds powerful time-based signals for note score changes, first-time diagnoses, and recency of events.
    SELECT
        MEMBER_ID,
        EVENT_DATE,
        -- Note Score Delta: Difference between current score and 30-day moving average.
        daily_agg.NOTE_HEALTH_SCORE - AVG(daily_agg.NOTE_HEALTH_SCORE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS NOTE_HEALTH_DELTA_30D,
        daily_agg.NOTE_RISK_HARM_SCORE - AVG(daily_agg.NOTE_RISK_HARM_SCORE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS NOTE_RISK_HARM_DELTA_30D,
        daily_agg.NOTE_SOCIAL_STAB_SCORE - AVG(daily_agg.NOTE_SOCIAL_STAB_SCORE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS NOTE_SOCIAL_STAB_DELTA_30D,
        daily_agg.NOTE_MED_ADHERENCE_SCORE - AVG(daily_agg.NOTE_MED_ADHERENCE_SCORE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS NOTE_MED_ADHERENCE_DELTA_30D,
        daily_agg.NOTE_CARE_ENGAGEMENT_SCORE - AVG(daily_agg.NOTE_CARE_ENGAGEMENT_SCORE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS NOTE_CARE_ENGAGEMENT_DELTA_30D,
        -- Days since last note for each category
        DATEDIFF(day, LAG(CASE WHEN daily_agg.NOTE_HEALTH_SCORE IS NOT NULL THEN daily_agg.EVENT_DATE ELSE NULL END) IGNORE NULLS OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE), daily_agg.EVENT_DATE) AS DAYS_SINCE_LAST_HEALTH_NOTE,
        DATEDIFF(day, LAG(CASE WHEN daily_agg.NOTE_RISK_HARM_SCORE IS NOT NULL THEN daily_agg.EVENT_DATE ELSE NULL END) IGNORE NULLS OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE), daily_agg.EVENT_DATE) AS DAYS_SINCE_LAST_RISK_NOTE,
        -- Recency flags for claims in the last 30 days.
        SUM(daily_agg.CNT_CLAIM_EVENTS) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS CLAIMS_IN_LAST_30D_COUNT,
        -- Recency flags for ED/IP events in the last 30 days.
        SUM(daily_agg.ANY_ED_ON_DATE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS ED_IN_LAST_30D_COUNT,
        SUM(daily_agg.ANY_IP_ON_DATE) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING) AS IP_IN_LAST_30D_COUNT,
        -- First-time diagnosis flags for all HCC categories.
        LAG(daily_agg.CNT_HCC_DIABETES, 1, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 AND daily_agg.CNT_HCC_DIABETES > 0 AS IS_FIRST_DIABETES,
        LAG(daily_agg.CNT_HCC_MENTAL_HEALTH, 1, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 AND daily_agg.CNT_HCC_MENTAL_HEALTH > 0 AS IS_FIRST_MENTAL_HEALTH,
        LAG(daily_agg.CNT_HCC_CARDIOVASCULAR, 1, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 AND daily_agg.CNT_HCC_CARDIOVASCULAR > 0 AS IS_FIRST_CARDIOVASCULAR,
        LAG(daily_agg.CNT_HCC_PULMONARY, 1, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 AND daily_agg.CNT_HCC_PULMONARY > 0 AS IS_FIRST_PULMONARY,
        LAG(daily_agg.CNT_HCC_KIDNEY, 1, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 AND daily_agg.CNT_HCC_KIDNEY > 0 AS IS_FIRST_KIDNEY,
        LAG(daily_agg.CNT_HCC_SUD, 1, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 AND daily_agg.CNT_HCC_SUD > 0 AS IS_FIRST_SUD,
        -- Detects if a new prescription class has appeared in the last 30 days.
        CASE WHEN daily_agg.RX_DAYS_ANTIPSYCH > 0 AND LAG(daily_agg.RX_DAYS_ANTIPSYCH, 30, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 THEN 1 ELSE 0 END AS NEW_RX_ANTIPSYCH_30D,
        CASE WHEN daily_agg.RX_DAYS_INSULIN > 0 AND LAG(daily_agg.RX_DAYS_INSULIN, 30, 0) OVER (PARTITION BY MEMBER_ID ORDER BY EVENT_DATE) = 0 THEN 1 ELSE 0 END AS NEW_RX_INSULIN_30D
    FROM daily_agg
),
first_note AS (
    -- Step 3: Find the date of the very first 'CARE_NOTE' for each engaged member.
    SELECT
        t1.member_id,
        MIN(t1.event_date) AS first_note_date
    FROM TRANSFORMED_DATA._TEMP.EVENTS_DAILY_AGG AS t1
    JOIN TRANSFORMED_DATA._TEMP.EVENTS_WITH_LABELS_RX AS t2
        ON t1.member_id = t2.member_id AND t1.event_date = t2.event_date
    WHERE t2.event_type = 'CARE_NOTE'
    GROUP BY t1.member_id
),
first_hcc_dates AS (
    -- Step 4: Find the first diagnosis date for each specific HCC category.
    SELECT
        MEMBER_ID,
        MIN(CASE WHEN CNT_HCC_DIABETES > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_DIABETES_DATE,
        MIN(CASE WHEN CNT_HCC_MENTAL_HEALTH > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_MENTAL_HEALTH_DATE,
        MIN(CASE WHEN CNT_HCC_CARDIOVASCULAR > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_CARDIOVASCULAR_DATE,
        MIN(CASE WHEN CNT_HCC_PULMONARY > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_PULMONARY_DATE,
        MIN(CASE WHEN CNT_HCC_KIDNEY > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_KIDNEY_DATE,
        MIN(CASE WHEN CNT_HCC_SUD > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_SUD_DATE
    FROM daily_agg
    GROUP BY MEMBER_ID
),
first_rx_dates AS (
    -- Step 5: Find the first fill date for each specific medication cohort.
    SELECT
        MEMBER_ID,
        MIN(CASE WHEN RX_DAYS_ANTIPSYCH > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_ANTIPSYCH_DATE,
        MIN(CASE WHEN RX_DAYS_INSULIN > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_INSULIN_DATE,
        MIN(CASE WHEN RX_DAYS_ORAL_ANTIDIAB > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_ORAL_ANTIDIAB_DATE,
        MIN(CASE WHEN RX_DAYS_STATIN > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_STATIN_DATE,
        MIN(CASE WHEN RX_DAYS_BETA_BLOCKER > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_BETA_BLOCKER_DATE,
        MIN(CASE WHEN RX_DAYS_OPIOID > 0 THEN EVENT_DATE ELSE NULL END) AS FIRST_OPIOID_DATE
    FROM daily_agg
    GROUP BY MEMBER_ID
),
member_split AS (
    -- Step 6a: Create a member-level split for training and testing.
    -- This ensures that all records for a given member are in the same dataset.
    SELECT
        MEMBER_ID,
        CASE
            WHEN UNIFORM(0::float, 1::float, RANDOM()) < 0.8 THEN 'TRAIN'
            ELSE 'TEST'
        END AS dataset_split
    FROM (
        SELECT DISTINCT MEMBER_ID FROM daily_agg
    )
),
prepped_features AS (
    -- Step 6: Create a single comprehensive dataset with all engineered features.
    SELECT
        base.*,
        lf.NOTE_HEALTH_DELTA_30D,
        lf.NOTE_RISK_HARM_DELTA_30D,
        lf.NOTE_SOCIAL_STAB_DELTA_30D,
        lf.NOTE_MED_ADHERENCE_DELTA_30D,
        lf.NOTE_CARE_ENGAGEMENT_DELTA_30D,
        lf.DAYS_SINCE_LAST_HEALTH_NOTE,
        lf.DAYS_SINCE_LAST_RISK_NOTE,
        lf.CLAIMS_IN_LAST_30D_COUNT,
        lf.ED_IN_LAST_30D_COUNT,
        lf.IP_IN_LAST_30D_COUNT,
        lf.IS_FIRST_DIABETES,
        lf.IS_FIRST_MENTAL_HEALTH,
        lf.IS_FIRST_CARDIOVASCULAR,
        lf.IS_FIRST_PULMONARY,
        lf.IS_FIRST_KIDNEY,
        lf.IS_FIRST_SUD,
        lf.NEW_RX_ANTIPSYCH_30D,
        lf.NEW_RX_INSULIN_30D,
        fn.first_note_date,
        -- Calculate months since first diagnosis for each HCC.
        DATEDIFF(month, hcc.FIRST_DIABETES_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_DIABETES,
        DATEDIFF(month, hcc.FIRST_MENTAL_HEALTH_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_MENTAL_HEALTH,
        DATEDIFF(month, hcc.FIRST_CARDIOVASCULAR_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_CARDIOVASCULAR,
        DATEDIFF(month, hcc.FIRST_PULMONARY_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_PULMONARY,
        DATEDIFF(month, hcc.FIRST_KIDNEY_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_KIDNEY,
        DATEDIFF(month, hcc.FIRST_SUD_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_SUD,
        -- Calculate months since first fill for each RX class.
        DATEDIFF(month, rx.FIRST_ANTIPSYCH_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_ANTIPSYCH,
        DATEDIFF(month, rx.FIRST_INSULIN_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_INSULIN,
        DATEDIFF(month, rx.FIRST_ORAL_ANTIDIAB_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_ORAL_ANTIDIAB,
        DATEDIFF(month, rx.FIRST_STATIN_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_STATIN,
        DATEDIFF(month, rx.FIRST_BETA_BLOCKER_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_BETA_BLOCKER,
        DATEDIFF(month, rx.FIRST_OPIOID_DATE, base.EVENT_DATE) AS MONTHS_SINCE_FIRST_OPIOID,
        -- Time-based features extracted from the event date.
        DAYOFWEEK(base.EVENT_DATE) AS day_of_week,
        MONTH(base.EVENT_DATE) AS month,
        YEAR(base.EVENT_DATE) AS year,
        DATEDIFF(day, base.DOB, base.EVENT_DATE) / 365.25 AS age
    FROM daily_agg AS base
    LEFT JOIN longitudinal_features AS lf
        ON base.MEMBER_ID = lf.MEMBER_ID AND base.EVENT_DATE = lf.EVENT_DATE
    LEFT JOIN first_note AS fn
        ON base.MEMBER_ID = fn.MEMBER_ID
    LEFT JOIN first_hcc_dates AS hcc
        ON base.MEMBER_ID = hcc.MEMBER_ID
    LEFT JOIN first_rx_dates AS rx
        ON base.MEMBER_ID = rx.MEMBER_ID
)
SELECT
    -- Step 7: Final SELECT statement to create the modeling dataset.
    -- It includes all features, labels, and the final data split column.
    p.MEMBER_ID,
    p.EVENT_DATE,
    p.DOB,
    p.day_of_week,
    p.month,
    p.year,
    p.age,
    
    -- One-hot encoded features for categorical data.
    CASE WHEN p.GENDER = 'MALE' THEN 1 ELSE 0 END AS IS_MALE,
    CASE WHEN p.GENDER = 'FEMALE' THEN 1 ELSE 0 END AS IS_FEMALE,
    CASE WHEN p.ENGAGEMENT_GROUP = 'ENGAGED_IN_PROGRAM' THEN 1 ELSE 0 END AS IS_ENGAGED,
    CASE WHEN p.ENGAGEMENT_GROUP = 'SELECTED_NOT_ENGAGED' THEN 1 ELSE 0 END AS IS_SELECTED_NOT_ENGAGED,
    CASE WHEN p.ENGAGEMENT_GROUP = 'NOT_SELECTED_FOR_ENGAGEMENT' THEN 1 ELSE 0 END AS IS_NOT_SELECTED_FOR_ENGAGEMENT,
    
    CASE WHEN p.NORMALIZED_COVERAGE_CATEGORY = 'TANF' THEN 1 ELSE 0 END AS IS_CATEGORY_TANF,
    CASE WHEN p.NORMALIZED_COVERAGE_CATEGORY = 'EXPANSION' THEN 1 ELSE 0 END AS IS_CATEGORY_EXPANSION,
    CASE WHEN p.NORMALIZED_COVERAGE_CATEGORY = 'DSNP' THEN 1 ELSE 0 END AS IS_CATEGORY_DSNP,
    CASE WHEN p.NORMALIZED_COVERAGE_CATEGORY = 'ABD' THEN 1 ELSE 0 END AS IS_CATEGORY_ABD,
    
    -- All other aggregated and imputed features.
    p.MONTHS_SINCE_BATCHED,
    p.CNT_CLAIM_DX,
    p.CNT_CLAIM_PROC,
    p.CNT_CLAIM_REV,
    p.CNT_CLAIM_EVENTS,
    p.ANY_ED_ON_DATE,
    p.ANY_IP_ON_DATE,
    p.PAID_SUM,
    p.CNT_HCC_DIABETES,
    p.CNT_HCC_MENTAL_HEALTH,
    p.CNT_HCC_CARDIOVASCULAR,
    p.CNT_HCC_PULMONARY,
    p.CNT_HCC_KIDNEY,
    p.CNT_HCC_SUD,
    p.CNT_ANY_HCC,
    p.CNT_PROC_PSYCHOTHERAPY,
    p.CNT_PROC_PSYCHIATRIC_EVALS,
    p.NOTE_HEALTH_SCORE,
    p.NOTE_RISK_HARM_SCORE,
    p.NOTE_SOCIAL_STAB_SCORE,
    p.NOTE_MED_ADHERENCE_SCORE,
    p.NOTE_CARE_ENGAGEMENT_SCORE,
    p.NOTE_PROGRAM_TRUST_SCORE,
    p.NOTE_SELF_SCORE,
    p.HEALTH_POP_BASELINE,
    p.HEALTH_INDIV_BASELINE,
    p.RX_DAYS_ANY,
    p.RX_DAYS_ANTIPSYCH,
    p.RX_DAYS_INSULIN,
    p.RX_DAYS_ORAL_ANTIDIAB,
    p.RX_DAYS_STATIN,
    p.RX_DAYS_BETA_BLOCKER,
    p.RX_DAYS_OPIOID,
    p.INCONSISTENCY_MED_NONCOMPLIANCE,
    p.INCONSISTENCY_APPT_NONCOMPLIANCE,
    -- Newly added longitudinal and recency features.
    p.NOTE_HEALTH_DELTA_30D,
    p.NOTE_RISK_HARM_DELTA_30D,
    p.NOTE_SOCIAL_STAB_DELTA_30D,
    p.NOTE_MED_ADHERENCE_DELTA_30D,
    p.NOTE_CARE_ENGAGEMENT_DELTA_30D,
    p.DAYS_SINCE_LAST_HEALTH_NOTE,
    p.DAYS_SINCE_LAST_RISK_NOTE,
    p.CLAIMS_IN_LAST_30D_COUNT,
    p.ED_IN_LAST_30D_COUNT,
    p.IP_IN_LAST_30D_COUNT,
    p.IS_FIRST_DIABETES,
    p.IS_FIRST_MENTAL_HEALTH,
    p.IS_FIRST_CARDIOVASCULAR,
    p.IS_FIRST_PULMONARY,
    p.IS_FIRST_KIDNEY,
    p.IS_FIRST_SUD,
    p.NEW_RX_ANTIPSYCH_30D,
    p.NEW_RX_INSULIN_30D,
    p.MONTHS_SINCE_FIRST_DIABETES,
    p.MONTHS_SINCE_FIRST_MENTAL_HEALTH,
    p.MONTHS_SINCE_FIRST_CARDIOVASCULAR,
    p.MONTHS_SINCE_FIRST_PULMONARY,
    p.MONTHS_SINCE_FIRST_KIDNEY,
    p.MONTHS_SINCE_FIRST_SUD,
    p.MONTHS_SINCE_FIRST_ANTIPSYCH,
    p.MONTHS_SINCE_FIRST_INSULIN,
    p.MONTHS_SINCE_FIRST_ORAL_ANTIDIAB,
    p.MONTHS_SINCE_FIRST_STATIN,
    p.MONTHS_SINCE_FIRST_BETA_BLOCKER,
    p.MONTHS_SINCE_FIRST_OPIOID,


    -- The target variables (labels) for prediction.
    p.Y_ANY_30D,
    p.Y_ANY_60D,
    p.Y_ANY_90D,
    p.Y_ED_30D,
    p.Y_ED_60D,
    p.Y_ED_90D,
    p.Y_IP_30D,
    p.Y_IP_60D,
    p.Y_IP_90D,
    
    -- A new feature to isolate the impact of notes.
    CASE
        WHEN p.ENGAGEMENT_GROUP = 'ENGAGED_IN_PROGRAM' AND p.EVENT_DATE >= p.first_note_date
        THEN 1
        ELSE 0
    END AS HAS_CARE_NOTES_POST_PERIOD,

    -- The final dataset split column from the member_split CTE.
    ms.dataset_split
FROM
    prepped_features AS p
JOIN
    member_split AS ms
ON
    p.MEMBER_ID = ms.MEMBER_ID;
