USE DATABASE TRANSFORMED_DATA;
USE SCHEMA _TEMP;

SET member_months_table = 'TRANSFORMED_DATA._TEMP.INT_MEMBER_MONTHS_ORDERED';

-- Medication classes to evaluate
-- 1. Insulin
-- 2. Oral diabetic
-- 3. Beta blocker
-- 4. Opiate
-- 5. Antipsychotic

-- For each class, answer:
--   a) ever_prescribed
--   b) multiple drugs prescribed in last 3 months
--   c) mpr last 3 months (adherent if MPR >= 0.8)
--   d) missed refill this month
--   e) new drug this month

CREATE OR REPLACE TABLE TRANSFORMED_DATA._TEMP.AL_REG_PHARMACY_METRICS_SUMMARY AS


-- CTE: member_months
WITH member_months AS (  SELECT FH_ID, EFFECTIVE_MONTH_START FROM IDENTIFIER($member_months_table)
),
-- CTE: pharmacy_claims (all relevant claims)
pharmacy_claims AS (
  SELECT FH_ID, FILLED_DATE, NDC_CODE, NDC_CODE_11_DIGIT, PRIMARY_AGENT_DESC, ACTIVE_INGREDIENTS_NAME, PLAN_PAID_AMOUNT, IS_FH_ANTIPSYCHOTIC, IS_ANTIPSYCH_MED, IS_INSULIN, IS_ORAL_ANTIDIABETIC, IS_STATIN, IS_BETA_BLOCKER, IS_OPIATE_AGONISTS, DAYS_SUPPLY
  FROM TRANSFORMED_DATA._TEMP.AL_REG_ATTRIBUTED_MEMBERS_PHARMACY
),
-- CTE: ever_prescribed flags for each class
insulin_ever_prescribed AS (
  SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE FROM pharmacy_claims WHERE IS_INSULIN = 1 GROUP BY FH_ID
),
oral_antidiabetic_ever_prescribed AS (
  SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE FROM pharmacy_claims WHERE IS_ORAL_ANTIDIABETIC = 1 GROUP BY FH_ID
),
beta_blocker_ever_prescribed AS (
  SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE FROM pharmacy_claims WHERE IS_BETA_BLOCKER = 1 GROUP BY FH_ID
),
opiate_ever_prescribed AS (
  SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE FROM pharmacy_claims WHERE IS_OPIATE_AGONISTS = 1 GROUP BY FH_ID
),
antipsych_ever_prescribed AS (
  SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE FROM pharmacy_claims WHERE IS_ANTIPSYCH_MED = 1 GROUP BY FH_ID
),
-- CTE: last_3_months_claims for rolling metrics
last_3_months_claims AS (
  SELECT
  mm.FH_ID,
  mm.EFFECTIVE_MONTH_START,
  pc.FILLED_DATE,
  pc.NDC_CODE,
  pc.NDC_CODE_11_DIGIT,
  pc.PRIMARY_AGENT_DESC,
  pc.ACTIVE_INGREDIENTS_NAME,
  pc.PLAN_PAID_AMOUNT,
  pc.IS_FH_ANTIPSYCHOTIC,
  pc.IS_ANTIPSYCH_MED,
  pc.IS_INSULIN,
  pc.IS_ORAL_ANTIDIABETIC,
  pc.IS_STATIN,
  pc.IS_BETA_BLOCKER,
  pc.IS_OPIATE_AGONISTS,
  pc.DAYS_SUPPLY
  FROM member_months mm
  LEFT JOIN pharmacy_claims pc
    ON mm.FH_ID = pc.FH_ID
    AND pc.FILLED_DATE BETWEEN DATEADD(month, -2, mm.EFFECTIVE_MONTH_START) AND mm.EFFECTIVE_MONTH_START
),
-- CTE: multiple_drugs_last_3_months
multiple_drugs_last_3_months AS (
  SELECT
    FH_ID,
    EFFECTIVE_MONTH_START,
    COUNT(DISTINCT IFF(IS_INSULIN = 1, NDC_CODE, NULL)) AS NUM_INSULIN_DRUGS_LAST_3_MONTHS,
    COUNT(DISTINCT IFF(IS_ORAL_ANTIDIABETIC = 1, NDC_CODE, NULL)) AS NUM_ORAL_ANTIDIABETIC_DRUGS_LAST_3_MONTHS,
    COUNT(DISTINCT IFF(IS_BETA_BLOCKER = 1, NDC_CODE, NULL)) AS NUM_BETA_BLOCKER_DRUGS_LAST_3_MONTHS,
    COUNT(DISTINCT IFF(IS_OPIATE_AGONISTS = 1, NDC_CODE, NULL)) AS NUM_OPIATE_DRUGS_LAST_3_MONTHS,
    COUNT(DISTINCT IFF(IS_ANTIPSYCH_MED = 1, NDC_CODE, NULL)) AS NUM_ANTIPSYCH_DRUGS_LAST_3_MONTHS
  FROM last_3_months_claims
  GROUP BY FH_ID, EFFECTIVE_MONTH_START
),
-- CTE: mpr_last_3_months
mpr_last_3_months AS (
  SELECT
    FH_ID,
    EFFECTIVE_MONTH_START,
    SUM(IFF(IS_INSULIN = 1, DAYS_SUPPLY, 0)) / 90.0 AS INSULIN_MPR_LAST_3_MONTHS,
    SUM(IFF(IS_ORAL_ANTIDIABETIC = 1, DAYS_SUPPLY, 0)) / 90.0 AS ORAL_ANTIDIABETIC_MPR_LAST_3_MONTHS,
    SUM(IFF(IS_BETA_BLOCKER = 1, DAYS_SUPPLY, 0)) / 90.0 AS BETA_BLOCKER_MPR_LAST_3_MONTHS,
    SUM(IFF(IS_OPIATE_AGONISTS = 1, DAYS_SUPPLY, 0)) / 90.0 AS OPIATE_MPR_LAST_3_MONTHS,
    SUM(IFF(IS_ANTIPSYCH_MED = 1, DAYS_SUPPLY, 0)) / 90.0 AS ANTIPSYCH_MPR_LAST_3_MONTHS
  FROM (
    SELECT DISTINCT FH_ID, EFFECTIVE_MONTH_START, NDC_CODE, FILLED_DATE, DAYS_SUPPLY, IS_INSULIN, IS_ORAL_ANTIDIABETIC, IS_BETA_BLOCKER, IS_OPIATE_AGONISTS, IS_ANTIPSYCH_MED
    FROM last_3_months_claims
  )
  GROUP BY FH_ID, EFFECTIVE_MONTH_START
),
-- CTE: med_adherent flag
med_adherent AS (
  SELECT
    FH_ID,
    EFFECTIVE_MONTH_START,
    CASE WHEN INSULIN_MPR_LAST_3_MONTHS >= 0.8 THEN 1 ELSE 0 END AS INSULIN_MED_ADHERENT,
    CASE WHEN ORAL_ANTIDIABETIC_MPR_LAST_3_MONTHS >= 0.8 THEN 1 ELSE 0 END AS ORAL_ANTIDIABETIC_MED_ADHERENT,
    CASE WHEN BETA_BLOCKER_MPR_LAST_3_MONTHS >= 0.8 THEN 1 ELSE 0 END AS BETA_BLOCKER_MED_ADHERENT,
    CASE WHEN OPIATE_MPR_LAST_3_MONTHS >= 0.8 THEN 1 ELSE 0 END AS OPIATE_MED_ADHERENT,
    CASE WHEN ANTIPSYCH_MPR_LAST_3_MONTHS >= 0.8 THEN 1 ELSE 0 END AS ANTIPSYCH_MED_ADHERENT
  FROM mpr_last_3_months
),
-- CTE: missed_refill_this_month
missed_refill_this_month AS (
  -- Missed refill: flag 1 if member had a prescription for the drug class in the previous month but not in the current month
  SELECT
    mm.FH_ID,
    mm.EFFECTIVE_MONTH_START,
    IFF(prev_insulin.FH_ID IS NOT NULL AND curr_insulin.FH_ID IS NULL, 1, 0) AS INSULIN_MISSED_REFILL_THIS_MONTH,
    IFF(prev_oral.FH_ID IS NOT NULL AND curr_oral.FH_ID IS NULL, 1, 0) AS ORAL_ANTIDIABETIC_MISSED_REFILL_THIS_MONTH,
    IFF(prev_beta.FH_ID IS NOT NULL AND curr_beta.FH_ID IS NULL, 1, 0) AS BETA_BLOCKER_MISSED_REFILL_THIS_MONTH,
    IFF(prev_opiate.FH_ID IS NOT NULL AND curr_opiate.FH_ID IS NULL, 1, 0) AS OPIATE_MISSED_REFILL_THIS_MONTH,
    IFF(prev_antipsych.FH_ID IS NOT NULL AND curr_antipsych.FH_ID IS NULL, 1, 0) AS ANTIPSYCH_MISSED_REFILL_THIS_MONTH
  FROM member_months mm
  LEFT JOIN (
    SELECT FH_ID, FILLED_DATE FROM pharmacy_claims WHERE IS_INSULIN = 1
  ) curr_insulin ON mm.FH_ID = curr_insulin.FH_ID AND mm.EFFECTIVE_MONTH_START = curr_insulin.FILLED_DATE
  LEFT JOIN (
    SELECT FH_ID, DATEADD(month, 1, FILLED_DATE) AS NEXT_MONTH FROM pharmacy_claims WHERE IS_INSULIN = 1
  ) prev_insulin ON mm.FH_ID = prev_insulin.FH_ID AND mm.EFFECTIVE_MONTH_START = prev_insulin.NEXT_MONTH
  LEFT JOIN (
    SELECT FH_ID, FILLED_DATE FROM pharmacy_claims WHERE IS_ORAL_ANTIDIABETIC = 1
  ) curr_oral ON mm.FH_ID = curr_oral.FH_ID AND mm.EFFECTIVE_MONTH_START = curr_oral.FILLED_DATE
  LEFT JOIN (
    SELECT FH_ID, DATEADD(month, 1, FILLED_DATE) AS NEXT_MONTH FROM pharmacy_claims WHERE IS_ORAL_ANTIDIABETIC = 1
  ) prev_oral ON mm.FH_ID = prev_oral.FH_ID AND mm.EFFECTIVE_MONTH_START = prev_oral.NEXT_MONTH
  LEFT JOIN (
    SELECT FH_ID, FILLED_DATE FROM pharmacy_claims WHERE IS_BETA_BLOCKER = 1
  ) curr_beta ON mm.FH_ID = curr_beta.FH_ID AND mm.EFFECTIVE_MONTH_START = curr_beta.FILLED_DATE
  LEFT JOIN (
    SELECT FH_ID, DATEADD(month, 1, FILLED_DATE) AS NEXT_MONTH FROM pharmacy_claims WHERE IS_BETA_BLOCKER = 1
  ) prev_beta ON mm.FH_ID = prev_beta.FH_ID AND mm.EFFECTIVE_MONTH_START = prev_beta.NEXT_MONTH
  LEFT JOIN (
    SELECT FH_ID, FILLED_DATE FROM pharmacy_claims WHERE IS_OPIATE_AGONISTS = 1
  ) curr_opiate ON mm.FH_ID = curr_opiate.FH_ID AND mm.EFFECTIVE_MONTH_START = curr_opiate.FILLED_DATE
  LEFT JOIN (
    SELECT FH_ID, DATEADD(month, 1, FILLED_DATE) AS NEXT_MONTH FROM pharmacy_claims WHERE IS_OPIATE_AGONISTS = 1
  ) prev_opiate ON mm.FH_ID = prev_opiate.FH_ID AND mm.EFFECTIVE_MONTH_START = prev_opiate.NEXT_MONTH
  LEFT JOIN (
    SELECT FH_ID, FILLED_DATE FROM pharmacy_claims WHERE IS_ANTIPSYCH_MED = 1
  ) curr_antipsych ON mm.FH_ID = curr_antipsych.FH_ID AND mm.EFFECTIVE_MONTH_START = curr_antipsych.FILLED_DATE
  LEFT JOIN (
    SELECT FH_ID, DATEADD(month, 1, FILLED_DATE) AS NEXT_MONTH FROM pharmacy_claims WHERE IS_ANTIPSYCH_MED = 1
  ) prev_antipsych ON mm.FH_ID = prev_antipsych.FH_ID AND mm.EFFECTIVE_MONTH_START = prev_antipsych.NEXT_MONTH
),
-- CTE: new_drug_this_month
new_drug_this_month AS (
  -- New drug: flag 1 if member received a drug (NDC_CODE) for the first time in the current month
  SELECT
    mm.FH_ID,
    mm.EFFECTIVE_MONTH_START,
    IFF(new_insulin.FH_ID IS NOT NULL, 1, 0) AS INSULIN_NEW_DRUG_THIS_MONTH,
    IFF(new_oral.FH_ID IS NOT NULL, 1, 0) AS ORAL_ANTIDIABETIC_NEW_DRUG_THIS_MONTH,
    IFF(new_beta.FH_ID IS NOT NULL, 1, 0) AS BETA_BLOCKER_NEW_DRUG_THIS_MONTH,
    IFF(new_opiate.FH_ID IS NOT NULL, 1, 0) AS OPIATE_NEW_DRUG_THIS_MONTH,
    IFF(new_antipsych.FH_ID IS NOT NULL, 1, 0) AS ANTIPSYCH_NEW_DRUG_THIS_MONTH
  FROM member_months mm
  LEFT JOIN (
    SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE, NDC_CODE FROM pharmacy_claims WHERE IS_INSULIN = 1 GROUP BY FH_ID, NDC_CODE
  ) new_insulin ON mm.FH_ID = new_insulin.FH_ID AND mm.EFFECTIVE_MONTH_START = new_insulin.FIRST_FILL_DATE
  LEFT JOIN (
    SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE, NDC_CODE FROM pharmacy_claims WHERE IS_ORAL_ANTIDIABETIC = 1 GROUP BY FH_ID, NDC_CODE
  ) new_oral ON mm.FH_ID = new_oral.FH_ID AND mm.EFFECTIVE_MONTH_START = new_oral.FIRST_FILL_DATE
  LEFT JOIN (
    SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE, NDC_CODE FROM pharmacy_claims WHERE IS_BETA_BLOCKER = 1 GROUP BY FH_ID, NDC_CODE
  ) new_beta ON mm.FH_ID = new_beta.FH_ID AND mm.EFFECTIVE_MONTH_START = new_beta.FIRST_FILL_DATE
  LEFT JOIN (
    SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE, NDC_CODE FROM pharmacy_claims WHERE IS_OPIATE_AGONISTS = 1 GROUP BY FH_ID, NDC_CODE
  ) new_opiate ON mm.FH_ID = new_opiate.FH_ID AND mm.EFFECTIVE_MONTH_START = new_opiate.FIRST_FILL_DATE
  LEFT JOIN (
    SELECT FH_ID, MIN(FILLED_DATE) AS FIRST_FILL_DATE, NDC_CODE FROM pharmacy_claims WHERE IS_ANTIPSYCH_MED = 1 GROUP BY FH_ID, NDC_CODE
  ) new_antipsych ON mm.FH_ID = new_antipsych.FH_ID AND mm.EFFECTIVE_MONTH_START = new_antipsych.FIRST_FILL_DATE
)
-- Final SELECT: combine all metrics
SELECT
  mm.FH_ID,
  mm.EFFECTIVE_MONTH_START,
  -- Ever prescribed flags
  IFF(iep.FIRST_FILL_DATE IS NOT NULL, 1, 0) AS INSULIN_EVER_PRESCRIBED,
  IFF(oep.FIRST_FILL_DATE IS NOT NULL, 1, 0) AS ORAL_ANTIDIABETIC_EVER_PRESCRIBED,
  IFF(bep.FIRST_FILL_DATE IS NOT NULL, 1, 0) AS BETA_BLOCKER_EVER_PRESCRIBED,
  IFF(oap.FIRST_FILL_DATE IS NOT NULL, 1, 0) AS OPIATE_EVER_PRESCRIBED,
  IFF(aep.FIRST_FILL_DATE IS NOT NULL, 1, 0) AS ANTIPSYCH_EVER_PRESCRIBED,
  -- Multiple drugs last 3 months
  mdt.NUM_INSULIN_DRUGS_LAST_3_MONTHS,
  mdt.NUM_ORAL_ANTIDIABETIC_DRUGS_LAST_3_MONTHS,
  mdt.NUM_BETA_BLOCKER_DRUGS_LAST_3_MONTHS,
  mdt.NUM_OPIATE_DRUGS_LAST_3_MONTHS,
  mdt.NUM_ANTIPSYCH_DRUGS_LAST_3_MONTHS,
  -- MPR last 3 months (null if never prescribed)
  CASE WHEN iep.FIRST_FILL_DATE IS NULL THEN NULL ELSE mpr.INSULIN_MPR_LAST_3_MONTHS END AS INSULIN_MPR_LAST_3_MONTHS,
  CASE WHEN oep.FIRST_FILL_DATE IS NULL THEN NULL ELSE mpr.ORAL_ANTIDIABETIC_MPR_LAST_3_MONTHS END AS ORAL_ANTIDIABETIC_MPR_LAST_3_MONTHS,
  CASE WHEN bep.FIRST_FILL_DATE IS NULL THEN NULL ELSE mpr.BETA_BLOCKER_MPR_LAST_3_MONTHS END AS BETA_BLOCKER_MPR_LAST_3_MONTHS,
  CASE WHEN oap.FIRST_FILL_DATE IS NULL THEN NULL ELSE mpr.OPIATE_MPR_LAST_3_MONTHS END AS OPIATE_MPR_LAST_3_MONTHS,
  CASE WHEN aep.FIRST_FILL_DATE IS NULL THEN NULL ELSE mpr.ANTIPSYCH_MPR_LAST_3_MONTHS END AS ANTIPSYCH_MPR_LAST_3_MONTHS,
  -- Med adherent flags (null if never prescribed)
  CASE WHEN iep.FIRST_FILL_DATE IS NULL THEN NULL ELSE ma.INSULIN_MED_ADHERENT END AS INSULIN_MED_ADHERENT,
  CASE WHEN oep.FIRST_FILL_DATE IS NULL THEN NULL ELSE ma.ORAL_ANTIDIABETIC_MED_ADHERENT END AS ORAL_ANTIDIABETIC_MED_ADHERENT,
  CASE WHEN bep.FIRST_FILL_DATE IS NULL THEN NULL ELSE ma.BETA_BLOCKER_MED_ADHERENT END AS BETA_BLOCKER_MED_ADHERENT,
  CASE WHEN oap.FIRST_FILL_DATE IS NULL THEN NULL ELSE ma.OPIATE_MED_ADHERENT END AS OPIATE_MED_ADHERENT,
  CASE WHEN aep.FIRST_FILL_DATE IS NULL THEN NULL ELSE ma.ANTIPSYCH_MED_ADHERENT END AS ANTIPSYCH_MED_ADHERENT,
  -- Missed refill flags
  mr.INSULIN_MISSED_REFILL_THIS_MONTH,
  mr.ORAL_ANTIDIABETIC_MISSED_REFILL_THIS_MONTH,
  mr.BETA_BLOCKER_MISSED_REFILL_THIS_MONTH,
  mr.OPIATE_MISSED_REFILL_THIS_MONTH,
  mr.ANTIPSYCH_MISSED_REFILL_THIS_MONTH,
  -- New drug flags
  nd.INSULIN_NEW_DRUG_THIS_MONTH,
  nd.ORAL_ANTIDIABETIC_NEW_DRUG_THIS_MONTH,
  nd.BETA_BLOCKER_NEW_DRUG_THIS_MONTH,
  nd.OPIATE_NEW_DRUG_THIS_MONTH,
  nd.ANTIPSYCH_NEW_DRUG_THIS_MONTH
FROM member_months mm
LEFT JOIN insulin_ever_prescribed iep ON mm.FH_ID = iep.FH_ID AND iep.FIRST_FILL_DATE <= mm.EFFECTIVE_MONTH_START
LEFT JOIN oral_antidiabetic_ever_prescribed oep ON mm.FH_ID = oep.FH_ID AND oep.FIRST_FILL_DATE <= mm.EFFECTIVE_MONTH_START
LEFT JOIN beta_blocker_ever_prescribed bep ON mm.FH_ID = bep.FH_ID AND bep.FIRST_FILL_DATE <= mm.EFFECTIVE_MONTH_START
LEFT JOIN opiate_ever_prescribed oap ON mm.FH_ID = oap.FH_ID AND oap.FIRST_FILL_DATE <= mm.EFFECTIVE_MONTH_START
LEFT JOIN antipsych_ever_prescribed aep ON mm.FH_ID = aep.FH_ID AND aep.FIRST_FILL_DATE <= mm.EFFECTIVE_MONTH_START
LEFT JOIN multiple_drugs_last_3_months mdt ON mm.FH_ID = mdt.FH_ID AND mm.EFFECTIVE_MONTH_START = mdt.EFFECTIVE_MONTH_START
LEFT JOIN mpr_last_3_months mpr ON mm.FH_ID = mpr.FH_ID AND mm.EFFECTIVE_MONTH_START = mpr.EFFECTIVE_MONTH_START
LEFT JOIN med_adherent ma ON mm.FH_ID = ma.FH_ID AND mm.EFFECTIVE_MONTH_START = ma.EFFECTIVE_MONTH_START
LEFT JOIN missed_refill_this_month mr ON mm.FH_ID = mr.FH_ID AND mm.EFFECTIVE_MONTH_START = mr.EFFECTIVE_MONTH_START
LEFT JOIN new_drug_this_month nd ON mm.FH_ID = nd.FH_ID AND mm.EFFECTIVE_MONTH_START = nd.EFFECTIVE_MONTH_START;
