-- 11_ed_ip_event_metrics.sql
-- ED/IP Event Metrics: In-month, last 3 months, last 3-6 months event counts
-- This table counts ED and IP events for each member/month, using both Place of Service and Revenue Code logic
-- Only includes months where member is enrolled
-- Output columns: FH_ID, EFFECTIVE_MONTH_START, ED_EVENTS_IN_MONTH, IP_EVENTS_IN_MONTH, ED_EVENTS_LAST_3_MONTHS, IP_EVENTS_LAST_3_MONTHS, ED_EVENTS_LAST_3_6_MONTHS, IP_EVENTS_LAST_3_6_MONTHS

CREATE OR REPLACE TABLE TRANSFORMED_DATA._TEMP.AL_REG_ATTRIBUTED_MEMBERS_ED_IP_EVENT_METRICS AS
WITH member_months AS (
  SELECT FH_ID, EFFECTIVE_MONTH_START
  FROM TRANSFORMED_DATA._TEMP.INT_MEMBER_MONTHS_ORDERED
  WHERE IS_ENROLLED = TRUE
),
ed_claims AS (
  SELECT FH_ID, CLAIM_START_DATE, claim_id
  FROM TRANSFORMED_DATA._TEMP.AL_REG_ATTRIBUTED_MEMBERS_CLAIMS
  WHERE CMS_REVENUE_CENTER_CODE IN ('0450', '0451', '0452', '0456', '0459', '0981')
),
ip_claims AS (
  SELECT FH_ID, CLAIM_START_DATE,claim_id
  FROM TRANSFORMED_DATA._TEMP.AL_REG_ATTRIBUTED_MEMBERS_CLAIMS
  WHERE CMS_REVENUE_CENTER_CODE IN ( '0100', '0110', '0120', '0130', '0140', '0150', '0160', '0170', '0180', '0190', '0200',  '0121', '0122', '0123', '0131', '0132', '0133', '0141', '0142', '0143', '0151', '0152', '0153')
),
metrics AS (
  SELECT
    mm.FH_ID,
    mm.EFFECTIVE_MONTH_START,
    -- In-month ED/IP event counts
    (SELECT COUNT(distinct claim_start_date) FROM ed_claims ec WHERE ec.FH_ID = mm.FH_ID AND ec.CLAIM_START_DATE >= mm.EFFECTIVE_MONTH_START AND ec.CLAIM_START_DATE < DATEADD('MONTH', 1, mm.EFFECTIVE_MONTH_START)) AS ED_EVENTS_IN_MONTH,
    (SELECT COUNT(distinct claim_start_date) FROM ip_claims ic WHERE ic.FH_ID = mm.FH_ID AND ic.CLAIM_START_DATE >= mm.EFFECTIVE_MONTH_START AND ic.CLAIM_START_DATE < DATEADD('MONTH', 1, mm.EFFECTIVE_MONTH_START)) AS IP_EVENTS_IN_MONTH,
    -- Last 3 months ED/IP event counts (includes current month)
    (SELECT COUNT(distinct claim_start_date) FROM ed_claims ec WHERE ec.FH_ID = mm.FH_ID AND ec.CLAIM_START_DATE >= DATEADD('MONTH', -2, mm.EFFECTIVE_MONTH_START) AND ec.CLAIM_START_DATE < DATEADD('MONTH', 1, mm.EFFECTIVE_MONTH_START)) AS ED_EVENTS_LAST_3_MONTHS,
    (SELECT COUNT(distinct claim_start_date) FROM ip_claims ic WHERE ic.FH_ID = mm.FH_ID AND ic.CLAIM_START_DATE >= DATEADD('MONTH', -2, mm.EFFECTIVE_MONTH_START) AND ic.CLAIM_START_DATE < DATEADD('MONTH', 1, mm.EFFECTIVE_MONTH_START)) AS IP_EVENTS_LAST_3_MONTHS,
    -- Last 3-6 months ED/IP event counts (months -5 to -2)
    (SELECT COUNT(distinct claim_start_date) FROM ed_claims ec WHERE ec.FH_ID = mm.FH_ID AND ec.CLAIM_START_DATE >= DATEADD('MONTH', -5, mm.EFFECTIVE_MONTH_START) AND ec.CLAIM_START_DATE < DATEADD('MONTH', -2, mm.EFFECTIVE_MONTH_START)) AS ED_EVENTS_LAST_3_6_MONTHS,
    (SELECT COUNT(distinct claim_start_date) FROM ip_claims ic WHERE ic.FH_ID = mm.FH_ID AND ic.CLAIM_START_DATE >= DATEADD('MONTH', -5, mm.EFFECTIVE_MONTH_START) AND ic.CLAIM_START_DATE < DATEADD('MONTH', -2, mm.EFFECTIVE_MONTH_START)) AS IP_EVENTS_LAST_3_6_MONTHS
  FROM member_months mm
)
SELECT * FROM metrics;
