CREATE OR REPLACE TABLE TRANSFORMED_DATA._TEMP.O as
SELECT 'START OF VALIDATIONS' AS VALIDATION_STEP, 0 AS ROW_COUNT, 0 AS UNIQUE_MEMBERS UNION ALL

-- 00 VALIDATE INPUT AND OUTPUT ATTRIBUTED MEMBERS
SELECT '00 - INPUT ATTRIBUTED MEMBERS' AS VALIDATION_STEP, COUNT(*) AS row_count, COUNT(DISTINCT FH_ID) AS       unique_members FROM TRANSFORMED_DATA._TEMP.AL_REG_ATTRIBUTED_MEMBERS UNION ALL
SELECT '00 - OUTPUT ATTRIBUTED MEMBERS' AS VALIDATION_STEP, COUNT(*) AS row_count, COUNT(DISTINCT FH_ID) AS       unique_members FROM TRANSFORMED_DATA._TEMP.INT_MEMBER_MONTHS_ORDERED UNION ALL
SELECT '00 - AVERAGE MEMBER MONTHS PER MEMBER' AS VALIDATION_STEP, COUNT(*) AS row_count, row_count/COUNT(DISTINCT FH_ID) AS  unique_members FROM TRANSFORMED_DATA._TEMP.INT_MEMBER_MONTHS_ORDERED UNION ALL
-- END OF ALL VALIDATIONS
SELECT '00 - NUMBER OF MEMBERS CONTINOUSL'
SELECT 'END OF VALIDATIONS' AS VALIDATION_STEP, 99 AS ROW_COUNT, 99 AS UNIQUE_MEMBERS;

select * from TRANSFORMED_DATA._TEMP.o